### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by ForNeVeR** [elamaunt/Soulstorm-GameSpy-Emulator#1]
Currently, the project doesn't state any license. Could you please state it?

If I am to be asked, I'd like to see a permissive one, like MIT or BSD or Apache-2.

**Comment by elamaunt** [comment]
> Currently, the project doesn't state any license. Could you please state it?
> 
> If I am to be asked, I'd like to see a permissive one, like MIT or BSD or Apache-2.

It's MIT. You may do everything you want.

**Comment by ForNeVeR** [comment]
That's great, but could you please clarify that somewhere near the sources? Thanks!

**Comment by ForNeVeR** [comment]
In particular, the MIT license requires me to attach a copy of the copyright notice if I fork the repository (or portions of code from it).

And it's kinda hard to copy the copyright notice if there's no notice to begin with 😅

**Comment by elamaunt** [comment]
> That's great, but could you please clarify that somewhere near the sources? Thanks!

Done
